name: keycloak-quickstart

include:
  - ./backend/docker-compose.yml

volumes:
  # Backup-Strategie bedenken!
  postgresKeycloakData: { }

services:
  keycloak:
    image: quay.io/keycloak/keycloak:${TAG_KC}
    # start-dev: nur für Entwicklung/Tests – nicht in Produktivumgebungen!
    command: start-dev
    depends_on:
      - keycloakdb
    environment:
      # Datenbank-Konfiguration
      KC_DB: postgres
      KC_DB_URL_HOST: keycloakdb
      KC_DB_USERNAME: ${DB_USER_KC}
      KC_DB_PASSWORD: ${DB_PW_KC}
      # Temporärer Admin für die Ersteinrichtung
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_ADMIN_PW}

      # Lokaler Cache, da nur eine Instanz verwendet wird
      KC_CACHE: local

      # Nur für lokale Entwicklung! HTTP aktivieren und Hostname-Validierung deaktivieren
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false
    ports:
      # HTTP-Port. Produktiv nur TLS nutzen!
      - "8080:8080"

  keycloakdb:
    image: postgres:${TAG_DB}
    ports:
      - "5432:5432"  # ← EXTERNER ZUGRIFF aktiviert nur für dev mode nötig
    restart: unless-stopped
    volumes:
      - postgresKeycloakData:/var/lib/postgresql
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${DB_USER_KC}
      POSTGRES_PASSWORD: ${DB_PW_KC}